#!/bin/bash
#                 .__      ___.   .__            .___.__
#  ________  _____|  |__   \_ |__ |__| ____    __| _/|__| ____    ____  ______
#  \___   / /  ___/  |  \   | __ \|  |/    \  / __ | |  |/    \  / ___\/  ___/
#   /    /  \___ \|   Y  \  | \_\ \  |   |  \/ /_/ | |  |   |  \/ /_/  >___ \
#  /_____ \/____  >___|  /  |___  /__|___|  /\____ | |__|___|  /\___  /____  >
#        \/     \/     \/       \/        \/      \/         \//_____/     \/


# backward and forward word with SHIFT + ARROW
# key codes determined using cat
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word

# ctrl + arrow key
bindkey "^[[1;5C" vi-forward-word-end
bindkey "^[[1;5D" vi-backward-word-end

__fsel() {
  local cmd="${FZF_CTRL_T_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type f -print \
    -o -type d -print \
    -o -type l -print 2> /dev/null | cut -b3-"}"
  setopt localoptions pipefail no_aliases 2> /dev/null
  eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" $(__fzfcmd) -m "$@" | while read item; do
    echo -n "${(q)item} "
  done
  local ret=$?
  echo
  return $ret
}

__fzf_use_tmux__() {
  [ -n "$TMUX_PANE" ] && [ "${FZF_TMUX:-0}" != 0 ] && [ ${LINES:-40} -gt 15 ]
}

__fzfcmd() {
  __fzf_use_tmux__ &&
    echo "fzf-tmux -d${FZF_TMUX_HEIGHT:-40%}" || echo "fzf"
}

fzf-file-widget() {
  \cd ~ || return
  LBUFFER="${LBUFFER}~/$(__fsel)"
  local ret=$?
  zle reset-prompt
  \cd - || return
  zle redisplay
  return $ret
}
zle     -N   fzf-file-widget
bindkey '^A' fzf-file-widget

# CTRL-R - Paste the selected command from history into the command line
fzf-history-widget() {
  local selected num
  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
  selected=( $(fc -rl 1 |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
  local ret=$?
  if [ -n "$selected" ]; then
    num=$selected[1]
    if [ -n "$num" ]; then
      zle vi-fetch-history -n $num
    fi
  fi
  zle reset-prompt
  return $ret
}
zle     -N   fzf-history-widget
bindkey '^R' fzf-history-widget

# Ensure precmds are run after cd
fzf-redraw-prompt() {
  local precmd
  for precmd in $precmd_functions; do
    $precmd
  done
  zle reset-prompt
}
zle -N fzf-redraw-prompt

backward-kill-dir () {
    local WORDCHARS=${WORDCHARS/\/}
    zle backward-kill-word
}

zle -N backward-kill-dir
bindkey '^W' backward-kill-dir

bindkey '^[[A' up-history
bindkey '^[[B' down-history
