#!/bin/bash
#                 .__      ___.   .__            .___.__
#  ________  _____|  |__   \_ |__ |__| ____    __| _/|__| ____    ____  ______
#  \___   / /  ___/  |  \   | __ \|  |/    \  / __ | |  |/    \  / ___\/  ___/
#   /    /  \___ \|   Y  \  | \_\ \  |   |  \/ /_/ | |  |   |  \/ /_/  >___ \
#  /_____ \/____  >___|  /  |___  /__|___|  /\____ | |__|___|  /\___  /____  >
#        \/     \/     \/       \/        \/      \/         \//_____/     \/


# backward and forward word with SHIFT + ARROW
# key codes determined using cat
bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word

# ctrl + arrow key
bindkey "^[[1;5C" vi-forward-word-end
bindkey "^[[1;5D" vi-backward-word-end

# fzf: override ctrl+t --> ctrl+w using homefolder
fzf-homefolder() {
    find ~ 2>/dev/null | fzf-tmux
}
zle     -N   fzf-homefolder
bindkey '^A' fzf-homefolder

# delete current word with ctrl+w
# bindkey "^W" backward-kill-word

backward-kill-dir () {
    local WORDCHARS=${WORDCHARS/\/}
    zle backward-kill-word
}

zle -N backward-kill-dir
bindkey '^W' backward-kill-dir

bindkey '^[[A' up-history
bindkey '^[[B' down-history
